-- CreateTable
CREATE TABLE "MMRSettings" (
    "id" SERIAL NOT NULL,
    "MMR_WIN_CHANGE" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "MMR_LOSS_CHANGE" DOUBLE PRECISION NOT NULL DEFAULT -1,
    "STREAK_BONUS" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "UNDERDOG_BONUS" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "POWER_DIFFERENCE_THRESHOLD" DOUBLE PRECISION NOT NULL DEFAULT 3,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MMRSettings_pkey" PRIMARY KEY ("id")
);
